config/routes.rb
Rails.application.routes.draw do
  get 'bets/create'
  get 'roulettes/create'
  get 'roulettes/index'
  get 'users/resta_saldo'

  root "roulettes#index"

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :user
  belongs_to :roulette
end

app/models/roulette.rb
class Roulette < ApplicationRecord

    has_many :bets
    

end

app/models/user.rb
class User < ApplicationRecord

    has_many :bets

end

app/controllers/api_controller.rb
class ApiController < ApplicationController
    def self.call_api
        require "uri"
        require "net/http"
        require "json"

        url = URI("https://api.openweathermap.org/data/2.5/onecall?lat=-33.45694&lon=-70.64827&exclude=minutely,hourly,current&units=metric&fields=temp&appid=7776823366e5dca08cf00319c3c436fa")

        https = Net::HTTP.new(url.host, url.port)
        https.use_ssl = true

        request = Net::HTTP::Get.new(url)

        response = https.request(request)
        body = JSON.parse response.read_body 
        
        b=[]
        body["daily"].each do |a|
            if a["temp"]["max"] > 32
                b << a["temp"]["max"]
            end 
        end

        multiplier = 0

        if b.any? 
            multiplier = (8+(rand*7).round(1))/100
        else
            multiplier = (3+(rand*4).round(1))/100
        end
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bets_controller.rb
class BetsController < ApiController

  def get_random()
    case rand(100) + 1
      when  1..49   then 'negro'
      when 49..98   then 'rojo'
      when 98..100  then 'verde'
    end
  end

  def user_bet

    if User.last.money <= 1000
      User.last.money
    else
      ApiController.call_api*User.last.money
    end

  end

  def create
    
    Bet.create(cash_bet: user_bet, color_bet: get_random, user_id: User.last.id, roulette_id: Roulette.last.id)  
    redirect_to users_resta_saldo_path
  end
end

app/controllers/roulettes_controller.rb
class RoulettesController < ApplicationController


  def get_random()
    case rand(100) + 1
      when  1..49   then 'negro'
      when 49..98   then 'rojo'
      when 98..100  then 'verde'
    end
  end


  def create
    
    @roulette = Roulette.create(result: get_random)
    redirect_to bets_create_path
    
  end


  def index

    
    @rolls = Roulette.all.order('created_at desc')
    @users = User.all

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def resta_saldo

    @user = User.last
    @bet = Bet.find(Bet.last.id)
    
    

    if Roulette.last.result == @bet.color_bet
      if @bet.color_bet == "verde"
        @user.money += Bet.last.cash_bet*15
      else
      @user.money += Bet.last.cash_bet 
      end
    else
      @user.money -= Bet.last.cash_bet
    end 
    @user.save






    redirect_to roulettes_index_path

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :money)
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/roulettes_helper.rb
module RoulettesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bets/create.html.erb
<h1>Bets#create</h1>
<p>Find me in app/views/bets/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruleta2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
    <%= link_to 'Ruletas', roulettes_index_path %>
    <%= link_to 'Jugadores', users_path %>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/roulettes/index.html.erb
<% if !@users.any? %>
  <p> Debes crear un usuario primero </p>

<% else %>

  <h1>Roulette</h1>
  <p>Aquí puedes rollear manualmente</p>
  <%= link_to "Roll", roulettes_create_path, method: :get %>
  <p>Usuario: <th><%= User.last.name %></th></p>
  <p>Saldo: <th><%= User.last.money %></th></p>
  <table>
    <thead>
      <tr>
        <th>Result</th>
        <th>Date</th>
        <th>Jugó</th>
        <th>Resultado</th>
        <th>Apuesta $</th>
        <th>Ganancia / Perdida</th>

      </tr>
    </thead>

    <tbody>
      <% @rolls.each do |draw| %>
        <tr>
          <td><%= draw.result %></td>
          <td><%= draw.result %></td>
          <td><%= draw.created_at %></td>

          <td>
              <% draw.bets.each do |bet| %>
              <%= bet.color_bet %>
              <% end %>
          </td>
          
          <td>
            <% if draw.result == draw.bets.map { |bet| bet.color_bet }[0]  %>
              <%= "Gano" %>
            <% else %>
              <%= "Perdió" %>
            <% end %>
          </td>
          
          <td>
            <% if draw.result == draw.bets.map { |bet| bet.color_bet }[0]  %>
              <%= draw.bets.map { |bet| bet.cash_bet }[0]  %>
            <% else %>
              <%= draw.bets.map { |bet| bet.cash_bet*-1 }[0]   %>
            <% end %>
          </td> 

          <td>
            <% if draw.result == draw.bets.map { |bet| bet.color_bet }[0]  %>
              <%  if draw.result == "verde" %>
                <%= draw.bets.map { |bet| bet.cash_bet }[0]*15  %>
              <% else %>
                <%= draw.bets.map { |bet| bet.cash_bet }[0]  %>
              <% end %>
            <% else %>
              <%= draw.bets.map { |bet| bet.cash_bet*-1 }[0]   %>
            <% end %>
          </td>



        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :money %>
    <%= form.number_field :money %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Money</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.money %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Money:</strong>
  <%= @user.money %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>



<table style="width:100%">
  <tr>
    <th>Spin</th>
    <th>Fecha</th> 
    <th>Apuesta</th>
    <th>Tombola</th>
    <th>Resultado</th>
    <th>Apuesta $</th>
    <th>Total $</th>
  </tr>
  <tr>
    <td>Numero spin</td>
    <td>Cuando fue</td> 
    <td>Rojo</td>
    <td>Rojo</td>
    <td>Gano</td>
    <td>500</td>
    <td>10500</td>
  </tr>

</table>